#!/bin/bash

: '

Author: Lander Usategui, lander.usategui@gmail.com

'
###########################
#       CONSTANTS         #
###########################
SET_NETWORK="/usr/bin/wpa_passphrase"
WPA_DIR="/etc/wpa_supplicant"

###########################
##      FUNCTIONS        ##
###########################
function firstMenu()
{
    OPTION=$(whiptail --title "What do you need?" --menu "Choose an option" 25 78 16 \
    "Connect to internet." ""\
    "Hotspot." "" 3>&1 1>&2 2>&3)

    case "$OPTION" in
       "Connect to internet.") internetMenu
       ;;
       "Hotspot.") hotspotMenu
       ;;
       "") whiptail --title "NOTE" --msgbox "Nothing to do, exiting..." 8 78
          exit 0
       ;;
    esac
}

function internetMenu()
{
  if [ "$(ifconfig | awk '{print $1}' | grep '^w' 2>/dev/null)" ]; then
    WIFI_DEVICES=($(ifconfig | awk '{print $1}' | grep '^e'))
    whiptail --title "Select device" --menu "Choose" 16 78 10 "" "${WIFI_DEVICES[@]}"
    internetConfig
  else
    whiptail --title "ERROR" --msgbox "No Wifi devices found..." 8 78
    exit 1
  fi

}

function internetConfig()
{
  NETWORK_NAME=$(whiptail --inputbox "Network name" 8 78 --title "Type the network name (SSID)" 3>&1 1>&2 2>&3)

  if [ "${NETWORK_NAME}" == "" ]; then
    whiptail --title "ERROR" --msgbox "Please, the name of the network is necessary..." 8 78
    exit 1
  elif [ $? = 0 ]; then
    whiptail --title "CANCEL" --msgbox "Exiting..." 8 78
    exit 1
  else
    PASSWORD=$(whiptail --passwordbox "Please, enter the password" 8 78 --title "password dialog" 3>&1 1>&2 2>&3)
    # Check password
    if [ "${PASSWORD}" == "" ]; then
      whiptail --title "ERROR" --msgbox "The password is necessary..." 8 78
      exit 1
    elif [ $? = 0 ]; then
      whiptail --title "CANCEL" --msgbox "Exiting..." 8 78
      exit 1
    else
      # Check password length needs between 8 and 63
      if [ ${#PASSWORD} -lt 8 ] || [ ${#PASSWORD} -gt 63 ]; then
        whiptail --title "ERROR" --msgbox "Passphrase must be 8..63 characters" 8 78
        exit 1
      else
        internetConnection
      fi
    fi
  fi

}

function internetConnection()
{

  {
    for ((i = 0 ; i <= 100 ; i+=5)); do
        sleep 0.05
        echo $i
    done
  } | whiptail --gauge "Configuring your network, please wait..." 6 50 0

  #Create file
  $SET_NETWORK $NETWORK_NAME $PASSWORD > $WPA_DIR/net.conf

}

function main()
{
  CURRENT_USER=$(whoami)

  if [ "${CURRENT_USER}" = "root" ]; then
  firstMenu
  else
    whiptail --title "ERROR" --msgbox "Launch the script with sudo...\n\"sudo ./wifiConfig\"" 8 78
  fi

}
###########################
##     END FUNCTIONS     ##
###########################

## Start script  ##
main
