#!/bin/bash

: '
    Author Lander Usategui, lander@erlerobotics.com
'

param=$1

function vanillaDeploy()
{
  cp Vanilla-4.9/kernel7.img /boot
  cp Vanilla-4.9/*.dtb /boot
  cp -r Vanilla-4.9/overlays /boot
  cp -r Vanilla-4.9/modulos/lib/firmware /lib
  cp -r Vanilla-4.9/modulos/lib/modules/4.9.13-v7+ /lib/modules
  echo "Done"
}

function rtDeploy()
{
  cp RT_4.9/kernel7.img /boot
  cp RT_4.9/*.dtb /boot
  cp -r RT_4.9/overlays /boot
  cp -r RT_4.9/modulos/lib/firmware /lib
  cp -r RT_4.9/modulos/lib/modules/4.9.13-rt12-v7+ /lib/modules
  if [ ! "`cat /boot/cmdline.txt | grep dwc_otg.fiq_enable=0\ dwc_otg.fiq_fsm_enable=0 2>/dev/null`" ]; then
	sed -i "1 s|$| dwc_otg.fiq_enable=0 dwc_otg.fiq_fsm_enable=0|" /boot/cmdline.txt
  fi
  echo "Done"
}

function preemptDeploy()
{
  cp PREEMPT_4.9/kernel7.img /boot
  cp PREEMPT_4.9/*.dtb /boot
  cp -r PREEMPT_4.9/overlays /boot
  cp -r PREEMPT_4.9/modulos/lib/firmware /lib
  cp -r PREEMPT_4.9/modulos/lib/modules/4.9.13-v7+ /lib/modules
  echo "Done"
}

function main()
{
  CURRENT_USER=`whoami`

  if [ "${CURRENT_USER}" = "root" ]; then
      if [ -z ${param} ]; then
    	echo "Pásale un parámetro, v,r,p"
      else
      	case "$param" in
        		"v" | "V") vanillaDeploy
        		;;
        		"r" | "R") rtDeploy
       		  ;;
        		"p" | "P") preemptDeploy
        		;;
        		*) echo "Unknown"
        		;;
  	     esac
     fi
  else
    echo "\"sudo\" is required..."
  fi
}

# Start script

main
