name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Install shellcheck
      run: sudo apt update && sudo apt install shellcheck -y
    - name: Linter checks
      run: bash ci-script.sh
